
/**
* Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* Tuesday, November 26, 2013 11:12:28 AM BRST
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
