
/**
* ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* Monday, November 25, 2013 2:05:22 PM BRST
*/

public interface ClientOperations 
{
  int updateTagValues (String tag_name, String tag_values);
} // interface ClientOperations
