
/**
* ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* Tuesday, November 26, 2013 11:12:28 AM BRST
*/

public interface ClientOperations 
{
  int updateTagValues (String tag_name, org.omg.CORBA.Any tag_values);
} // interface ClientOperations
