package org.br.corbaSupport.service;


/**
* ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Monday, November 25, 2013 6:45:23 PM BRST
*/

public interface ServiceOperations 
{
  int updateSensorValues (String sensor_name, String tag_name, String tag_values);
  int registerClient (String client_name, String first_tag, String second_tag);
} // interface ServiceOperations
