package org.br.corbaSupport.service;


/**
* ServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Monday, November 25, 2013 2:09:00 PM BRST
*/

public final class ServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Service value = null;

  public ServiceHolder ()
  {
  }

  public ServiceHolder (Service initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServiceHelper.type ();
  }

}
