package org.br.corbaSupport.service;


/**
* Service.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Monday, November 25, 2013 6:45:23 PM BRST
*/

public interface Service extends ServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Service
