package org.br.corbaSupport.sensor;


/**
* SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Monday, November 25, 2013 3:41:52 PM BRST
*/

public interface SensorOperations 
{
} // interface SensorOperations
