package org.br.corbaSupport.sensor;


/**
* Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sensor.idl
* Monday, November 25, 2013 3:41:52 PM BRST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
