package org.br.corbaSupport.client;


/**
* _ClientStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* Tuesday, November 26, 2013 11:12:28 AM BRST
*/

public class _ClientStub extends org.omg.CORBA.portable.ObjectImpl implements Client
{

  public int updateTagValues (String tag_name, org.omg.CORBA.Any tag_values)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateTagValues", true);
                $out.write_string (tag_name);
                $out.write_any (tag_values);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateTagValues (tag_name, tag_values        );
            } finally {
                _releaseReply ($in);
            }
  } // updateTagValues

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Client:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ClientStub
