package org.br.corbaSupport.client;


/**
* Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* Monday, November 25, 2013 2:05:22 PM BRST
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
